addSbtPlugin("com.github.gseitz" % "sbt-release"   % "1.0.13")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"       % "2.0.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.4.6")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.7.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "3.9.13")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo" % "0.11.0")
