name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os   :    [ubuntu-latest]
        scala:    [2.12.17, 2.13.10, 3.2.0]
        platform: [jvm]
        java :    [8, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: olafurpg/setup-scala@v13
        with:
          java-version: "adopt@1.${{ matrix.java }}"

      - name: Cache
        uses: coursier/cache-action@v5

      - name: Test
        run: sbt ++${{ matrix.scala }} validate
